<?php

namespace App\Http\Requests;

use App\Exceptions\ThrottleException;
use App\Reply;
use App\Rules\SpamFree;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Gate;

class CreatPostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return Gate::allows('create',new Reply);
    }

    protected function failedAuthorization()
    {
       // parent::failedAuthorization(); // TODO: Change the autogenerated stub

        throw new ThrottleException('You are replying too frequently');
    }


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "body"=>["required",new SpamFree]
        ];
    }

    public function persist($thread){
        return $thread->addReply(
            [
                'body'=>\request('body'),
                'user_id'=>auth()->id()
            ])->load('owner');
    }
}
